#!/bin/bash
# Shell script to handle VDR post-recording actions, like noad, H264 conversions
# Based on VDR example
#------------------------------------------------------------------------------
# Revision History
#
# Removed --asd as it was moving the cut marks to the wrong places
# Removd -C (scene change detection) which seems to mess up marks unecessarily
#------------------------------------------------------------------------------
#
# $Log: vdr-auto,v $
# Revision 1.2  2018/09/12 13:20:05  richard
# Updated for vdr-convert V2.2 with --podcast option
#
#------------------------------------------------------------------------------

case "$1" in
     before)
            echo "Before recording $2"
            ;;
     started)
            # some recent library change causes noad to barf with "started" (which was never a supported switch!)
            echo "Started recording $2"
            /usr/local/bin/noad -s /etc/vdr/noadstat.csv -o -c before $2
            ;;
     after)
            echo "After recording $2"
            #vdr forks this script, noad forks itself, vdr-convert doesn't
            /usr/local/bin/noad -s /etc/vdr/noadstat.csv -o -c  $1 $2
            /usr/local/bin/vdr-convert -a libfdk_aac -k -c -d --podcast /mnt/lvm/Radio -g /etc/vdr/xmltv2vdr/genres.conf -i $2 &
            ;;
     edited)
            echo "Edited recording $2"
            ;;
     deleted)
            echo "Deleted recording $2"
            ;;
     *)
            echo "ERROR: unknown state: $1"
            ;;
esac

# --------- $Id: vdr-auto,v 1.2 2018/09/12 13:20:05 richard Exp $ ---------- END
